{% set name = "pyjanitor" %}
{% set version = "0.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyjanitor-devs/pyjanitor/archive/v0.22.0.tar.gz
  sha256: 44226035abd4be56a786f745f0afbdf46902a2a1885231928d51af063340f904

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - multipledispatch
    - natsort
    - pandas
    - pandas-flavor
    - requests
    - scikit-learn
    - scipy
    - xarray
    - xlrd

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - janitor
    - janitor.accessors

about:
  home: https://github.com/pyjanitor-devs/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for cleaning pandas DataFrames
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/pyjanitor-devs/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
    - ocefpaf
